"""code"""
import math
push = int(input())
sit = int(input())
squat = int(input())
run = int(input())
pushday = int(input())
sitday = int(input())
runday = int(input())
squatday = int(input())
x = math.ceil(push / pushday)
y = math.ceil(sit / sitday)
z = math.ceil(squat / squatday)
v = math.ceil(run / runday)
minday = max(x, y, z, v)
print(minday)
